/**
 * @license
 * Copyright 2025 AionUi (aionui.com)
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Processing status for document intake pipeline
 */
export type ProcessingStatus = 'pending' | 'extracting' | 'analyzing' | 'indexing' | 'complete' | 'failed';

/**
 * Document type classification
 */
export type DocumentType = 'Complaint' | 'Motion' | 'Response' | 'Order' | 'Notice' | 'Evidence' | 'Research' | 'Unknown';

/**
 * File type for supported document formats
 */
export type FileType = 'pdf' | 'docx' | 'txt' | 'md' | 'jpg' | 'png' | 'mp3' | 'wav' | 'm4a' | 'unknown';

/**
 * Case Document entity - matches migration v12 schema
 * Represents a document uploaded to a case file
 */
export interface ICaseDocument {
  /** Unique document ID (UUID) */
  id: string;

  /** Foreign key to case_files table */
  case_file_id: string;

  /** Original filename */
  filename: string;

  /** Sanitized folder name for document storage */
  folder_name: string;

  /** Classified document type (Complaint, Motion, Evidence, etc.) */
  document_type?: string | null;

  /** File extension/type (pdf, docx, txt, etc.) */
  file_type: string;

  /** Number of pages extracted (PDF only) */
  page_count?: number | null;

  /** Total word count from extracted text */
  word_count?: number | null;

  /** Current processing status */
  processing_status: ProcessingStatus;

  /** Whether text extraction has completed (SQLite boolean: 0/1) */
  has_text_extraction: number;

  /** Whether AI metadata generation has completed (SQLite boolean: 0/1) */
  has_metadata: number;

  /** Whether document is indexed in RAG system (SQLite boolean: 0/1) */
  rag_indexed: number;

  /** Google File Search store ID (RAG indexing) */
  file_search_store_id?: string | null;

  /** Gemini Files API URI for this document */
  gemini_file_uri?: string | null;

  /** Upload timestamp (Unix milliseconds) */
  uploaded_at: number;

  /** Processing completion timestamp (Unix milliseconds) */
  processed_at?: number | null;

  // ========== S3 Storage Fields (added in migration v12) ==========

  /** S3 object key (full path in bucket) */
  s3_key?: string | null;

  /** S3 bucket name */
  s3_bucket?: string | null;

  /** S3 upload timestamp (Unix milliseconds) */
  s3_uploaded_at?: number | null;

  /** S3 version ID (if versioning is enabled) */
  s3_version_id?: string | null;

  /** MIME content type (e.g., application/pdf, video/mp4) */
  content_type?: string | null;

  /** File size in bytes */
  file_size_bytes?: number | null;
}

/**
 * Document metadata generated by AI analysis
 * Stored as JSON file in workspace
 */
export interface IDocumentMetadata {
  /** Schema version for future compatibility */
  schema_version: string;

  /** Reference to document ID in database */
  document_id: string;

  /** Original filename */
  original_filename: string;

  /** File type (pdf, docx, etc.) */
  file_type: string;

  /** Classified document type */
  document_type: DocumentType;

  /** AI confidence in classification (0.0 - 1.0) */
  classification_confidence: number;

  /** Text extraction details */
  extraction: {
    method: 'pdf-parse' | 'mistral-ocr' | 'plaintext' | 'docx';
    page_count?: number;
    word_count?: number;
    extracted_at: string; // ISO timestamp
  };

  /** AI-generated summary */
  summary: {
    executive_summary: string;
    main_arguments: string[];
    requested_relief?: string;
  };

  /** Extracted entities */
  entities: {
    parties: Array<{
      name: string;
      role: string;
      mentions: number;
    }>;
    dates: Array<{
      date: string;
      context: string;
      page?: number;
    }>;
    authorities?: Array<{
      citation: string;
      context: string;
    }>;
  };

  /** Relevance scoring by claim type */
  relevance_scores?: Record<string, number>;

  /** Cross-document relationships */
  relationships?: {
    references?: string[]; // Document IDs
    contradicts?: string[];
    supports?: string[];
  };

  /** RAG indexing details */
  rag?: {
    file_search_store_id: string;
    indexed_at: string;
    chunk_count?: number;
  };

  /** Agent annotations (for manual notes) */
  agent_notes?: string;

  /** User-provided notes/context about the document */
  user_notes?: string;
}

/**
 * Case documents manifest - generated view from database
 * Aggregates all documents and metadata for a case
 */
export interface ICaseDocumentsManifest {
  /** Schema version */
  schema_version: string;

  /** Case file ID */
  case_file_id: string;

  /** Last manifest update timestamp */
  last_updated: string; // ISO timestamp

  /** Total document count */
  document_count: number;

  /** All documents in case */
  documents: Array<{
    id: string;
    filename: string;
    folder_name: string;
    document_type?: string;
    relevance?: Record<string, string>; // claim type -> relevance level
    key_parties?: string[];
    important_dates?: string[];
    page_count?: number;
    has_text_extraction: boolean;
    has_metadata: boolean;
    rag_indexed: boolean;
    processing_status: ProcessingStatus;
    added_at: string; // ISO timestamp
  }>;

  /** Party registry (aggregated from all documents) */
  parties_registry?: Record<
    string,
    {
      role: string;
      documents: string[]; // document IDs
    }
  >;

  /** Timeline (aggregated from all documents) */
  timeline?: Array<{
    date: string;
    event: string;
    source_doc: string; // document ID
  }>;

  /** Claims (aggregated) */
  claims?: string[];
}

/**
 * Filter query for document searches
 */
export interface FilterQuery {
  /** Filter by document types */
  document_types?: DocumentType[];

  /** Filter by date range */
  date_range?: {
    start: Date;
    end: Date;
  };

  /** Filter by party names */
  parties?: string[];

  /** Filter by text extraction status */
  has_text_extraction?: boolean;

  /** Filter by metadata status */
  has_metadata?: boolean;

  /** Filter by processing status */
  processing_status?: ProcessingStatus[];

  /** Combine filters with AND (default) or OR */
  combineWith?: 'AND' | 'OR';
}

/**
 * Manifest entry for a single document
 * Used in case-documents-manifest.json
 */
export interface ManifestEntry {
  /** Document ID */
  id: string;

  /** Original filename */
  filename: string;

  /** Sanitized folder name */
  folder_name: string;

  /** Classified document type */
  document_type?: string;

  /** Number of pages */
  page_count?: number;

  /** Word count */
  word_count?: number;

  /** Whether text extraction completed */
  has_text_extraction: boolean;

  /** Whether metadata generation completed */
  has_metadata: boolean;

  /** Whether RAG indexing completed */
  rag_indexed: boolean;

  /** Current processing status */
  processing_status: ProcessingStatus;

  /** Timestamp when document was added */
  added_at: string;

  /** File paths relative to workspace */
  paths: {
    original: string;
    extraction?: string;
    metadata?: string;
  };
}

/**
 * Helper: Convert SQLite boolean (0/1) to TypeScript boolean
 */
export function sqliteBoolToBoolean(value: number): boolean {
  return value === 1;
}

/**
 * Helper: Convert TypeScript boolean to SQLite boolean (0/1)
 */
export function booleanToSqliteBool(value: boolean): number {
  return value ? 1 : 0;
}
